apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-db
  template:
    metadata:
      labels:
        app: student-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
